### PR TITLE
Refactor running Starknet commands; Fix devnet interaction on macOS+venv

### LINKED ISSUE #27: Issues connecting to local devnet
Hi,

When trying to run mocha tests on a local devnet (i.e. `http://localhost:5000`), Hardhat cannot connect to the network

```
yarn run v1.22.10
$ hardhat test
Starknet plugin using the active environment.


  Account
    1) should deploy the Account contract


  0 passing (3s)
  1 failing

  1) Account
       should deploy the Account contract:
     HardhatPluginError: Could not deploy contract. Check the network url in config. Is it responsive?
      at StarknetContractFactory.<anonymous> (node_modules/@shardlabs/starknet-hardhat-plugin/src/types.ts:223:19)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/@shardlabs/starknet-hardhat-plugin/dist/types.js:24:58)
```

You can see my hardhat.config.ts file here
```
import "@shardlabs/starknet-hardhat-plugin";
import { HardhatUserConfig } from "hardhat/config";

const config: HardhatUserConfig = {
  cairo: {
    venv: 'active',
  },
  defaultNetwork: 'devnet',
  networks: {
    devnet: {
      url: 'http://localhost:5000',
    }
  },
  mocha: {
    starknetNetwork: 'devnet',
  }
};

export default config;
```

I tried using both `nile node` and `starknet-devnet` and both fail.

I really like the ability to use Hardhat for Cairo development as well and keep Cairo and Solidity in the same project. Fixing this issue would really help in a major Cairo/StarkNet integration.

Setup:
macOS 12.0.1
python 3.8.9
cairo-lang 0.6.1

### PR DESCRIPTION
**Pull request by FabijanC**
## Usage
- Fix path documentation for `starknet-verify`.
- Support different mainnet namings (so far only `alphaMainnet` was supported, now `alpha-mainnet` is also).

## Dev
- Refactor `StarknetWrapper.runCommand` to: `compile`, `deploy`, `getTxStatus`, `invokeOrCall`.
- Make the macOS localhost adaptations only in `DockerWrapper`:
  - Interacting with `starknet-devnet` on macOS using `venv` is now fixed (@octate please approve this PR if you find this to be true).
  - Closes #27

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -270,7 +243,10 @@ function isTestnet(networkName: string): boolean {
  */
 function getGatewayUrl(args: any, hre: HardhatRuntimeEnvironment): string {
     let gatewayUrl: string = args.gatewayUrl;
-    const networkName: string = args.starknetNetwork || process.env.STARKNET_NETWORK;
+    let networkName: string = args.starknetNetwork || process.env.STARKNET_NETWORK;
+    if (isMainnet(networkName)) {
+        networkName = ALPHA_MAINNET_INTERNALLY;
+    }
```
Comment (FabijanC) [inline src/index.ts:250]: @dribeiro-ShardLabs During the rebase, I guess I should have added an `isTestnet` check here; right?

Comment (dribeiro-ShardLabs) [reply src/index.ts:250]: Yes, so we use our internal naming for testnet as well

File: src/index.ts [hunk 2]
```diff
@@ -331,45 +302,40 @@ task("starknet-deploy", "Deploys Starknet contracts which have been compiled.")
...
             console.log("Checking deployment transactions...");
-            const promises = txHashes.map( hash => new Promise<void>((resolve, reject) => {iterativelyCheckStatus(
+            const promises = txHashes.map( hash => new Promise<void>((resolve, reject) => iterativelyCheckStatus(
                 hash, 
                 hre.starknetWrapper, 
                 gatewayUrl, 
                 gatewayUrl, 
                 () => {
-                    console.log("Deployment transaction " + hash + " status is now PENDING");
+                    console.log("Deployment transaction " + hash + " status is now at least PENDING");
```
Comment (dribeiro-ShardLabs) [inline src/index.ts:331]: Should change to "at least ACCEPTED_ON_L2", right? That's what we are waiting for during the iterative check

**Review by dribeiro-ShardLabs — APPROVED** [review]

**Review by octate — APPROVED** [review]
