### PR TITLE
Fix devnet-related test failure

### LINKED ISSUE #249: CI/CD tests fail with Devnet 0.3.5
Evidence: this commit fixes CI/CD: https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/243/commits/a65393b91ba83d4146e0b3857097d000b5e43501

### PR DESCRIPTION
**Pull request by FabijanC**
## Usage related changes

- Use integrated-devnet v0.3.5 by default

## Development related changes

- Close #249 
- Update to `starknet-devnet` v0.3.5
- Update `test.sh`
  - Kill devnet subprocess by name (`pkill`)
- Update .circlec/config.yml
  - Update circleci executor to `ubuntu-2004:2022.10.1`
  - Reduce comments (keep all info)
- The branch name is `update-node-14` because I thought updating would help

### CODE REVIEW

File: test/general-tests/predeployed-accounts-test/check.sh [hunk 1]
```diff
@@ -1,4 +1,5 @@
 #!/bin/bash
 set -e
 
+lsof -i :5050
```
Comment (Nathan-SL) [inline test/general-tests/predeployed-accounts-test/check.sh:4]: Why do we need this?

Comment (FabijanC) [reply test/general-tests/predeployed-accounts-test/check.sh]: Accidentally left this debugging line, removed it here: https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/253/commits/a836aa58a35ca9e79550838f83eb953df3644e5a

**Review by Nathan-SL — APPROVED** [review]
