### PR TITLE
Fix Docker Connection Timed out

### LINKED ISSUE #209: Error in plugin Starknet: starknet-docker-proxy-20959113038453658 connection timed out!
From what users have said, my guess is that it's a problem with reaching the proxy server inside a docker container on mac host machines.

### PR DESCRIPTION
**Pull request by Nathan-SL**
## Usage related changes

-   Removes network mode from docker args and uses port mapping in place for arm64 machine.
-   Closes #209 

## Development related changes

-   NA

## Checklist:

-   [x] Formatted the code
-   [x] No linter errors + tried to avoid introducing linter warnings
-   [x] Performed a self-review of the code
-   [x] Rebased to the last commit of the target branch (or merged it into my branch)
-   [ ] Documented the changes
-   [ ] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.sh`)
-   [x] Linked issues which this PR resolves
-   [ ] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
    -   < EXAMPLE_REPO_PR_URL > 
    -   [ ] Modified `test.sh` to use my example repo branch
    -   [ ] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
-   [x] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

### CODE REVIEW

File: src/starknet-docker-proxy.ts [hunk 1]
```diff
@@ -32,7 +32,17 @@ export class StarknetDockerProxy extends DockerServer {
             volumes.push("-v", `${mirroredPath}:${mirroredPath}`);
         }
 
-        return [...volumes, "--network", "host"];
+        const dockerArgs = [...volumes];
+        // Check host machine
+        const isArm64 = process.arch === "arm64";
```
Comment (FabijanC) [inline src/starknet-docker-proxy.ts:37]: This is an os problem, not an architecture one, the check for mac should be done as in `adaptUrl`

File: src/starknet-docker-proxy.ts [hunk 2]
```diff
@@ -32,7 +32,17 @@ export class StarknetDockerProxy extends DockerServer {
...
+        if (isArm64) {
+            this.port = await getFreePort();
```
Comment (FabijanC) [inline src/starknet-docker-proxy.ts:39]: As discussed, there should be only one place where `getFreePort` is called. We could introduce a `getPort` method which returns `this.port` if defined, otherwise calls `getFreePort` before that. The new method would have to return a Promise (i.e. be async).

**Review by FabijanC — CHANGES_REQUESTED** [review]

File: src/starknet-docker-proxy.ts (hunk 1 above)
Comment (Nathan-SL) [reply src/starknet-docker-proxy.ts]: https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/210/commits/73d4039c6eca8654e2f5d2d306b506f9d213cf1b

File: src/starknet-docker-proxy.ts (hunk 2 above)
Comment (Nathan-SL) [reply src/starknet-docker-proxy.ts]: https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/210/commits/73d4039c6eca8654e2f5d2d306b506f9d213cf1b
