### PR TITLE
Declare return tx hash

### LINKED ISSUE #313: Class declaration should return transaction hash instead of class hash
Rationale:
- class hash can be retrieved in other ways (`contractFactory.getClassHash()`)
- there is no way of getting the transaction hash if it failed

This would be a breaking change.

### PR DESCRIPTION
**Pull request by TsBauer**
## Usage related changes

-  `declare()` now returns the tx instead of the class hash
- Now, the user needs to check the tx status for validating a successful declaration
- Closes #313 (breaking)

## Development related changes

-   N/A

## Checklist:

-   [x] Formatted the code
-   [x] No linter errors + tried to avoid introducing linter warnings
-   [x] Performed a self-review of the code
-   [x] Rebased to the last commit of the target branch (or merged it into my branch)
-   [x] Documented the changes
-   [x] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.ts`)
-   [x] Linked issues which this PR resolves (#313)
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
    -   https://github.com/Shard-Labs/starknet-hardhat-example/pull/103
    -   [x] Modified `test.sh` to use my example repo branch
    -   [x] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
-   [x] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)

### CODE REVIEW

File: src/types/index.ts [hunk 1]
```diff
@@ -382,19 +382,9 @@ export class StarknetContractFactory {
...
 
         const executedOutput = executed.stdout.toString();
-        const classHash = extractClassHash(executedOutput);
         const txHash = extractTxHash(executedOutput);
 
-        return new Promise((resolve, reject) => {
-            iterativelyCheckStatus(
-                txHash,
-                this.hre.starknetWrapper,
-                () => resolve(classHash),
```
Comment (FabijanC) [inline src/types/index.ts:392]: My idea was to keep on iteratively checking status, but eventually resolving not with `classHash` but with `txHash`, since the class hash can be obtained in different ways (`contractFactory.getClassHash()` as mentioned in #313).

Your change would make declare txs the only ones which don't wait for the transaction to become accepted. Ideally all transactions would behave the same (or is there an advantage in treating declaration differently?)

File: www/docs/intro.md [hunk 2]
```diff
@@ -307,8 +308,13 @@ it("should estimate fee", async function () {
 it("should forward to the implementation contract", async function () {
     const implementationFactory = await starknet.getContractFactory("contract");
     const account = ...;
-    const implementationClassHash = await account.declare(implementationFactory);
+    const txHash = await account.declare(implementationFactory);
 
+    // ensure that tx has been successful
+    const txReceipt = await starknet.getTransactionReceipt(txHash);
+    expect(txReceipt.status).to.equal("ACCEPTED_ON_L2" || "ACCEPTED_ON_L1");
```
Comment (FabijanC) [inline www/docs/intro.md:315]: How should this work? Shouldn't some waiting have to be done? This is related to my other comment about potentially reverting to awaiting inside of `declare`.

**Review by FabijanC — CHANGES_REQUESTED** [review]
The issue-linking mentioned in the checklist refers to actually making your PR automatically close the issue once it's merged to master. I achieved this by editing your PR description (added the keyword `Closes`).

Also, since the last time you contributed, we have enabled CircleCI workflow for outside contributors. I see a test of yours is failing (you can check it by clicking on :x:  here on the PR page). Probably you didn't await a declaration.

If some tests pass without awaiting their tx to become accepted, it's probably because they are run on Devnet, which by default accepts them upon receival. On real networks this acceptance is not instant.

File: src/types/index.ts (hunk 1 above)
Comment (TsBauer) [reply src/types/index.ts:392]: Fair point. Consistency is king. This will be changed👍

**Comment by FabijanC** [comment]
@TsBauer @Dl-Vv I see that you applied some changes. Is your PR then ready for another round of review?

I would appreciate if you could paste relevant commit links as replies to my existing comments (can simply be copied from the PR discussion page, e.g. https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/332/commits/b4f961d083b7b87abe130f6866df2f113b43fb3d - GitHub styles them like this automatically). I would also appreciate if you could then formally request my review here on GitHub when you are ready.

Thanks

File: src/types/index.ts (hunk 1 above)
Comment (TsBauer) [reply src/types/index.ts:392]: Re-introduced iterative checking in  3662a4435bca6a25e6c0193d87dd5d5a45474c27.

**Comment by TsBauer** [comment]
@FabijanC Got it. We'll make it a habit👍

File: scripts/test.sh [hunk 3]
```diff
@@ -9,13 +9,13 @@ CONFIG_FILE_NAME="hardhat.config.ts"
 
 # setup example repo
 rm -rf starknet-hardhat-example
-EXAMPLE_REPO_BRANCH="plugin"
-if [[ "$CIRCLE_BRANCH" == "master" ]] && [[ "$EXAMPLE_REPO_BRANCH" != "plugin" ]]; then
+EXAMPLE_REPO_BRANCH="plugin-declare-return-tx-hash"
```
Comment (FabijanC) [inline scripts/test.sh:12]: Thanks for appropriately modifying test.sh. You can revert it now that https://github.com/Shard-Labs/starknet-hardhat-example/pull/103 has been merged.

**Review by FabijanC — APPROVED** [review]
Looks good, thanks for the contribution! Just revert the repo and branch used in `test.sh`.

File: scripts/test.sh (hunk 3 above)
Comment (TsBauer) [reply scripts/test.sh]: Done: 0d5a6c8d8e6f8bc08accf8911281fb5baa3f4a60

**Comment by TsBauer** [comment]
It's a pleasure to contribute🙏
