### PR TITLE
Adapt to Starknet 0.10.0

### LINKED ISSUE #211: Declaring class hash fails
I might be missing out on something but I'm getting the following error:

`StarknetPluginError: Could not declare class: Error: AssertionError: Sender must be passed explicitly when making a direct declaration using --no_wallet.`

After running: 

 ```
const l2BridgeFactory = await starknet.getContractFactory("bridge");
const  l2BridgeImplHash = await l2BridgeFactory.declare(); //<--->getting error at this level
```

My current setup:
- python = "^3.9"
- cairo-lang = "^0.10.0"
- starknet-devnet = "^0.3.0"

### LINKED ISSUE #215: Stop logging outside of rejection / throwing
Currently in some places we do e.g. `console.error(...)` which may confuse users who might be expecting their tx to fail in a test, as was the case in #214. So instead of doing custom error logs, all error text should be wrapped in Promise rejections and throwing Errors.

### LINKED ISSUE #217: StarknetErrorCode.OUT_OF_RANGE_FEE for class declaration
Trying to declare my contract class on Goerli using: 
`const bridgeImplHash = await deployer.declare(L2BridgeFactory, {maxFee: 1e18});`

Results in the following error 

`StarknetPluginError: Could not declare class: Got BadRequest while trying to access https://alpha4.starknet.io/gateway/add_transaction. Status code: 500; text: {"code": "StarknetErrorCode.OUT_OF_RANGE_FEE", "message": "max_fee must be bigger than 0.\n0 >= 0"}.`

@FabijanC

### PR DESCRIPTION
**Pull request by FabijanC**
## Usage related changes

- Adapt to cairo-lang/Starknet v0.10.0
- Currently works with https://github.com/Shard-Labs/starknet-hardhat-plugin#wallet
  - [This example](https://github.com/Shard-Labs/starknet-hardhat-example/blob/adapt-starknet-0.10.0/test/wallet-test.ts) works if the wallet address has funds (e.g. on Devnet use [mint](https://github.com/Shard-Labs/starknet-devnet#mint-token---local-faucet))
- Deprecate `account.call(contract, ...)`; use `contract.call(...)` instead.
- Introduced signed declaration through account with `Account.declare(...)`:
    - Instead of `contractFactory.declare()`, do `account.declare(contractFactory, { maFee: ... /*optional*/ })`
    - Close #211 
    - Close #217
- Introduced `starknet.getNonce(address: string)` utility function
- Use adapted implementation of OpenZeppelin accounts ([our fork of v0.4.0b](https://github.com/Shard-Labs/cairo-contracts/tree/fix-account-query-version)).
- Remove redundant logging - close #215
- Release plugin v0.6.6

## Development related changes

- Adapt fee estimation, calling, declaring
- Use cairo-lang 0.10.0
- Use Devnet 0.3.1
- Modify starknet_cli_wrapper.py to allow calculating class hash (don't know of a js way to do that so we are using cairo-lang's way to handle it)
- Introduce `getExecuteArgs` to class `Account` since OZ and Argent now differ in that regard (the `__execute__` method of the former doesn't require the nonce argument anymore)
- Remove tests which are testing unsupported functionality (like calling with account or passing signature to calls)

## Checklist:

-   [x] Formatted the code
-   [x] No linter errors + tried to avoid introducing linter warnings
-   [x] Performed a self-review of the code
-   [x] Rebased to the last commit of the target branch (or merged it into my branch)
-   [x] Documented the changes
-   [x] Updated the `test` directory (with a test case consisting of `network.json`, `hardhat.config.ts`, `check.sh`)
-   [x] Updated `starknet-invoke` tests to use a wallet
-   [x] Linked issues which this PR resolves
-   [x] Created a PR to the `plugin` branch of [`starknet-hardhat-example`](https://github.com/Shard-Labs/starknet-hardhat-example):
    -   https://github.com/Shard-Labs/starknet-hardhat-example/pull/80
    -   [x] Modified `test.sh` to use my example repo branch
    -   [x] Restored `test.sh` to to use the original branch (after the example repo PR has been merged)
-   [ ] All tests are passing (for external contributors who don't have access to the CI/CD pipeline)
-   [x] Restored package.json version

### CODE REVIEW

**Comment by FabijanC** [comment]
Waiting for https://github.com/OpenZeppelin/cairo-contracts/pull/449

File: src/starknet-wrappers.ts [hunk 1]
```diff
@@ -127,6 +140,15 @@ export abstract class StarknetWrapper {
...
         }
 
+        if (options.sender) {
+            prepared.push("--sender", options.sender);
+        }
+
+        if (options.maxFee == null) {
+            throw new StarknetPluginError("No maxFee provided for declare tx");
+        }
+        prepared.push("--max_fee", options.maxFee);
```
Comment (hsouf) [inline src/starknet-wrappers.ts:150]: Thank you for adding this!

Comment (FabijanC) [reply src/starknet-wrappers.ts:150]: A new version should be released today. If we manage to get all the tests passing, it will be 0.6.6, otherwise it will be 0.6.6-alpha.4

Comment (hsouf) [reply src/starknet-wrappers.ts:150]: Cool, looking forward to it!

**Review by Nathan-SL — APPROVED** [review]
LGTM!
